// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7joA8ljBQoRtPePgNdOVEtdiDDO5_m8s',
    appId: '1:896323058310:web:a146a2d23c2dc95631af07',
    messagingSenderId: '896323058310',
    projectId: 'pdf-points-de6d9',
    authDomain: 'pdf-points-de6d9.firebaseapp.com',
    storageBucket: 'pdf-points-de6d9.appspot.com',
    measurementId: 'G-5EGEHC9NZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_kX4-8Uzgk6t9xI8ntqlC4FTCsoxm8Gg',
    appId: '1:896323058310:android:98b546962e518e6431af07',
    messagingSenderId: '896323058310',
    projectId: 'pdf-points-de6d9',
    storageBucket: 'pdf-points-de6d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRAc1RPYXJ1YGu9H8rx1EJCda9YoE6hg',
    appId: '1:896323058310:ios:1d1bce9c42aeb3b731af07',
    messagingSenderId: '896323058310',
    projectId: 'pdf-points-de6d9',
    storageBucket: 'pdf-points-de6d9.appspot.com',
    iosBundleId: 'com.example.pdfPoints',
  );

}